config/routes.rb
Rails.application.routes.draw do
  resources :timetables
  resources :notes
  resources :docs
  resources :application_settings
  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "/doc/show_all" => "docs#show_all"
  post "/doc/create_partial" => "docs#create_partial"
  get "/doc/show" => "docs#show"
  get "/doc/index" => "docs#index"
  post "/doc/update_partial" => "docs#update_partial"
  post "/timetable/update_partial" => "timetables#update_partial"
  post "/note/show_teacher_notes" => "notes#show_teacher_notes"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_setting.rb
class ApplicationSetting < ApplicationRecord
end

app/models/class_doc.rb
class ClassDoc < ApplicationRecord
end

app/models/class_group.rb
class ClassGroup < ApplicationRecord
end

app/models/doc.rb
class Doc < ApplicationRecord
end

app/models/doc_group.rb
class DocGroup < ApplicationRecord
end

app/models/doc_type.rb
class DocType < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/setup.rb
class Setup < ApplicationRecord
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  #belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/models/user_type.rb
class UserType < ApplicationRecord
end

app/controllers/application_settings_controller.rb
class ApplicationSettingsController < ApplicationController
  skip_before_action :verify_authenticity_token

  # GET /application_settings
  # GET /application_settings.json
  def index
    @application_settings = ApplicationSetting.all
  end

  # GET /application_settings/1
  # GET /application_settings/1.json
  def show
  end

  # GET /application_settings/new
  def new
    @application_setting = ApplicationSetting.new
  end

  # GET /application_settings/1/edit
  def edit
  end

  # POST /application_settings
  # POST /application_settings.json
  def create
       set_to_class = User.find(params[:user_id])
       if set_to_class.user_type_id == 2
           if Setup.find_by_class_id(set_to_class.class_id).blank?
             object = Setup.new
             object.class_id = set_to_class.class_id
             object.enabled_apps = params[:content]
           object.save!
           elsif !Setup.find_by_class_id(set_to_class.class_id).blank?
             object = Setup.find_by_class_id(set_to_class.class_id)
             object.enabled_apps = params[:content]
             object.save!
           end
       end
       return true
  end

  # PATCH/PUT /application_settings/1
  # PATCH/PUT /application_settings/1.json
  def update
    respond_to do |format|
      if @application_setting.update(application_setting_params)
        format.html { redirect_to @application_setting, notice: 'Application setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @application_setting }
      else
        format.html { render :edit }
        format.json { render json: @application_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_settings/1
  # DELETE /application_settings/1.json
  def destroy
    @application_setting.destroy
    respond_to do |format|
      format.html { redirect_to application_settings_url, notice: 'Application setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_setting
      @application_setting = ApplicationSetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_setting_params
      params.require(:application_setting).permit(:setup)
    end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def index
      if !params[:edit_id].blank?
      @doc_id = Doc.find(params[:edit_id])
      end
      #doc_type_id = DocType.find_by_doc_name(params[:doc_type])
    render file: Rails.public_path.join("features","editor.html.erb"), layout: false, :object => @doc_id, :user_type_id => params[:user_type_id] #, :doc_type_id => doc_type_id
    end

    def create_partial
      get_user = User.find(session[:current_user])
      get_doc =  DocType.find_by_doc_name(params[:doc_type])
      if !get_user.blank?
        object = Doc.new
        object.doc_headline = params[:doc_headline]
        object.doc_content = params[:doc_content]
        object.user_id = get_user.id
        object.doc_type_id = get_doc.id
        if get_user.user_type_id == 3
          object.doc_group_id = 1 # in doc_groups 2 = Vorlage
        else
          if !params[:choosed_value].blank?
            object.doc_group_id = 2 # Vorlage oder Eigene Docs bei lehrer
          else
            object.doc_group_id = 1 #Wenn nicht ausgewählt ist speichert er in eigene Dokumente
          end
        end
        object.save!
        session[:your_key] = object.id
        if get_user.user_type_id != 3
          choosed_classes = params[:choosed_value].split(",")
          choosed_classes.each do |value|
            value_id = ClassGroup.find(value).id
            object = ClassDoc.new
            object.doc_id = session[:your_key]
            object.class_id = value_id
            object.save
          end
        end
      else
        redirect_to :action => "login"
      end
      render file: "docs/show", layout: false, :object => object.id
end

  def update_partial
   get_user = User.find(session[:current_user])
   get_doc =  Doc.find(params[:doc_id])
   if !get_user.blank?
     object = get_doc
     object.doc_headline = params[:doc_headline]
     object.doc_content = params[:doc_content]
#     object.user_id = get_user.id
#     object.doc_type_id = get_doc.id
     object.save!
     session[:your_key] = object.id
#      params[:choosed_value].length.to_i.times do | value |
#        object = ClassDoc.new
#        object.doc_id = session[:your_key]
#        object.class_id = value
#        object.save
#      end

   else
    redirect_to :action => "login"
   end
  render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  def show
    if !params[:choosed_doc].blank?
    session[:your_key] = params[:choosed_doc]
    @doc_id = Doc.find(session[:your_key])
     session[:your_key] = nil
     render file: "docs/show", layout: false, :object => @doc_id
   else
     render file: Rails.public_path.join("features","editor.html.erb"), layout: false
   end

  end

  def show_all
      @doc_id = params[:params]
      @doc_type = params[:doc_type]
     render file: 'docs/show_all'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/application_settings_helper.rb
module ApplicationSettingsHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application_settings/_form.html.erb
<%= form_with(model: application_setting, local: true) do |form| %>
  <% if application_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application_setting.errors.count, "error") %> prohibited this application_setting from being saved:</h2>

      <ul>
      <% application_setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :setup %>
    <%= form.text_field :setup %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/application_settings/edit.html.erb
<h1>Editing Application Setting</h1>

<%= render 'form', application_setting: @application_setting %>

<%= link_to 'Show', @application_setting %> |
<%= link_to 'Back', application_settings_path %>

app/views/application_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Application Settings</h1>

<table>
  <thead>
    <tr>
      <th>Setup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @application_settings.each do |application_setting| %>
      <tr>
        <td><%= application_setting.setup %></td>
        <td><%= link_to 'Show', application_setting %></td>
        <td><%= link_to 'Edit', edit_application_setting_path(application_setting) %></td>
        <td><%= link_to 'Destroy', application_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application Setting', new_application_setting_path %>

app/views/application_settings/new.html.erb
<h1>New Application Setting</h1>

<%= render 'form', application_setting: @application_setting %>

<%= link_to 'Back', application_settings_path %>

app/views/application_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Setup:</strong>
  <%= @application_setting.setup %>
</p>

<%= link_to 'Edit', edit_application_setting_path(@application_setting) %> |
<%= link_to 'Back', application_settings_path %>